name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Build with Xcode
        working-directory: ./demo
        run: xcodebuild -workspace demo.xcodeproj -scheme demo -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
